SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR>=9 AND HOUR<20
ORDER BY HOUR(DATETIME)

# GROUP BY와 ORDER BY 절에서 HOUR(DATETIME) 대신 HOUR로 해도 OK
# SELECT절의 COUNT안에는 HOUR(dATETIME), DATETIME, * 모두 가능
